services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - "./db:/var/lib/postgresql/data/"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - production.env
    restart: unless-stopped
  django:
    build: .
    env_file:
      - production.env
    environment:
      - STATIC_ROOT=/code/static
      - DB_HOST=db
      - DB_PORT=5432
      - PROMETHEUS_METRICS_EXPORT_PORT_RANGE=8001-8019
      - DJANGO_DEBUG=0
    ports:
      - 3830:80
      - "3851-3869:8001-8019"
    volumes:
      - "./user_upload:/code/user_upload"
      - "/var/www/html/geochron@home/static/:/code/static/"
      - "./vendor:/code/vendor"
    restart: unless-stopped
    depends_on:
      - db
