# Generated by Django 3.1.5 on 2021-02-02 18:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=36, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]+$', 'Only alphanumeric, "-" and "_" are allowed.')])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('project_description', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default='0')),
                ('closed', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'create_date',
                'unique_together': {('project_name', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=36, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]+$', 'Only alphanumeric, "-" and "_" are allowed.')])),
                ('sample_property', models.CharField(choices=[('T', 'Test Sample'), ('A', 'Age Standard Sample'), ('D', 'Dosimeter Sample')], default='T', max_length=1)),
                ('total_grains', models.IntegerField()),
                ('priority', models.IntegerField(default='0')),
                ('min_contributor_num', models.IntegerField(default='1')),
                ('completed', models.BooleanField(default=False)),
                ('in_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftc.project')),
            ],
            options={
                'unique_together': {('sample_name', 'in_project')},
            },
        ),
        migrations.CreateModel(
            name='FissionTrackNumbering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain', models.IntegerField()),
                ('ft_type', models.CharField(choices=[('S', 'Spontaneous Fission Tracks'), ('I', 'Induced Fission Tracks')], max_length=1)),
                ('result', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('latlngs', models.TextField(default='')),
                ('in_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftc.sample')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('in_sample', 'grain', 'ft_type', 'worker', 'create_date')},
            },
        ),
    ]
