# Generated by Django 4.0.2 on 2022-03-01 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0003_tutorialresult'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fissiontracknumbering',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grain',
            name='scale_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='grain',
            name='scale_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='grain',
            name='stage_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='grain',
            name='stage_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='focus',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='light_path',
            field=models.CharField(choices=[('T', 'Transmitted Light'), ('R', 'Reflected Light')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=36, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]+$', 'Only alphanumeric, "-" and "_" are allowed.')]),
        ),
        migrations.AlterUniqueTogether(
            name='grain',
            unique_together={('sample', 'index')},
        ),
    ]
