# Generated by Django 4.1.2 on 2022-12-02 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0006_alter_grain_scale_x_alter_grain_scale_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(max_length=36, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\- #/\\(\\):@]+$', 'Only alphanumeric, space and "_-#():@" are allowed.')]),
        ),
    ]
