# Generated by Django 4.1.2 on 2022-12-15 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0007_alter_sample_sample_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transform2D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x0', models.FloatField()),
                ('y0', models.FloatField()),
                ('t0', models.FloatField()),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('t1', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='grain',
            name='mica_stage_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grain',
            name='mica_stage_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grain',
            name='mica_transform_matrix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ftc.transform2d'),
        ),
    ]
