# Generated by Django 4.1.2 on 2023-02-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0008_transform2d_grain_mica_stage_x_grain_mica_stage_y_and_more'),
    ]

    operations = [
        migrations.RenameField('FissionTrackNumbering', 'grain', 'grain_index')
    ]
