# Generated by Django 4.1.2 on 2023-02-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0009_rename_ftn_grain_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='fissiontracknumbering',
            name='grain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ftc.grain'),
        ),
    ]
