# Generated by Django 4.1.2 on 2023-02-01 15:20

from django.db import migrations

def populate_ftn_grain(apps, schema_editor):
    FissionTrackNumbering = apps.get_model('ftc', 'FissionTrackNumbering')
    Grain = apps.get_model('ftc', 'Grain')
    for ftn in FissionTrackNumbering.objects.all():
        ftn.grain = Grain.objects.get(sample=ftn.in_sample, index=ftn.grain_index)
        ftn.save()

def depopulate_ftn_grain(apps, schema_editor):
    FissionTrackNumbering = apps.get_model('ftc', 'FissionTrackNumbering')
    for ftn in FissionTrackNumbering.objects.all():
        ftn.grain = None
        ftn.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0010_fissiontracknumbering_grain'),
    ]

    operations = [
        migrations.RunPython(populate_ftn_grain, depopulate_ftn_grain)
    ]
