# Generated by Django 4.1.2 on 2023-02-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0011_populate_ftn_grain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fissiontracknumbering',
            name='grain_index',
        ),
        migrations.RemoveField(
            model_name='fissiontracknumbering',
            name='in_sample',
        ),
    ]
