# Generated by Django 4.1.7 on 2023-03-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0013_alter_fissiontracknumbering_grain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='total_grains',
        ),
    ]
