# Generated by Django 4.1.7 on 2023-06-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0017_transform_latlngs_to_grainpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fissiontracknumbering',
            name='latlngs',
        ),
        migrations.AlterField(
            model_name='grainpointcategory',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
