# Generated by Django 4.1.7 on 2023-08-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0019_tutorialpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ftc.grainpointcategory'),
        ),
    ]
