# Generated by Django 4.1.7 on 2023-11-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0021_alter_grainpointcategory_options_tutorialpage_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
