# Generated by Django 4.2.7 on 2024-07-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0023_containedtrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='fissiontracknumbering',
            name='analyst',
            field=models.TextField(null=True),
        ),
    ]
