# Generated by Django 4.2.7 on 2024-07-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftc', '0024_fissiontracknumbering_analyst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containedtrack',
            name='z1_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='containedtrack',
            name='z2_level',
            field=models.IntegerField(),
        ),
    ]
