# Generated by Django 5.1.5 on 2025-01-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ftc', '0025_alter_containedtrack_z1_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='groups_who_have_access',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
